# Specify maintainers
Maintainers:
 - Preston Sego
 - Akram Mnif

# Specify base image
From: node:7.9.0

# Specify a user that the service will run as, used for fixing permissions on volumes.
User: root

# Specify environment variables
Env:
 - PATH : '$PATH:/usr/local/lib/node_modules'

# Run commands verbatim in bash format. Note the pipe character.
Run: |
 # Create web directory
 mkdir /web

 # Install Google Chrome Stable version
 wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
 echo "deb http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google.list
 apt-get update
 apt-get install -y google-chrome-stable

 # Install archivers
 apt-get install tar bzip2

 # Install Ember CLI
 npm install -g ember-cli@2.13.3

 # Install Bower
 npm install -g bower@1.8.0

 # Allow root use
 echo '{ "allow_root": true }' > /root/.bowerrc

 # Install PhantomJS
 npm install -g phantomjs-prebuilt@2.1.14

 # Install watchman
 git clone https://github.com/facebook/watchman.git
 cd watchman
 git checkout v4.7.0  # the latest stable release
 ./autogen.sh
 ./configure
 make
 make install

# Ports to expose.
Expose:
 - 4200
 - 49152

# Command to run after launching container.
Command: 'ember server'

# Working directory from where all the commands must run
Work_Dir: /web
